name: Coveralls

on:
  push:
    branches:
      - main

jobs:
  setup-tarpaulin:
    runs-on: ubuntu-latest
    
    steps:
      - uses: taiki-e/install-action@cargo-tarpaulin
      
#   setup-rust:
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: Install Rust toolchain
#         uses: dtolnay/rust-toolchain@nightly
    
  setup-taos:
    runs-on: ubuntu-latest
    
    steps:
      - name: Cache taosc
        uses: actions/cache@v3
        with:
          key: taosc
          path: TDengine-client-3.0.7.1
    
      - name: Install taosc
        run: |
          curl -sO https://www.taosdata.com/assets-download/3.0/TDengine-client-3.0.7.1-Linux-x64-Lite.tar.gz
          tar zxf TDengine-client-3.0.7.1-Linux-x64-Lite.tar.gz
          cd TDengine-client-3.0.7.1
          ./install_client.sh
          
  coverage:
    needs: [setup-tarpaulin, setup-taos]
    runs-on: ubuntu-latest
    
    services:
      tdengine:
        image: tdengine/tdengine:3.0.7.1
        ports:
          - 6030:6030
    
    steps:
      - uses: actions/checkout@v3
            
      - name: Coverage
        run: cargo +nightly tarpaulin --follow-exec --post-test-delay 10 --coveralls ${{ secrets.COVERALLS_REPO_TOKEN }} -- --test-threads=1
