name: Coveralls

on:
  push:
    branches:
      - main

jobs:       
  coverage:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Get taos version
        run: |
          file_content=$(cat TAOSVERSION)
          echo "::set-env name=TAOS_VERSION::$file_content"
          
      - name: Start service
        run: docker run -d --name taosd -p 6030:6030 tdengine/tdengine:${{ env.TAOS_VERSION }}
      
      - uses: dtolnay/rust-toolchain@nightly
      
      - uses: taiki-e/install-action@cargo-tarpaulin
      
      - name: Cache taosc
        uses: actions/cache@v3
        with:
          key: taosc
          path: TDengine-client-${{ env.TAOS_VERSION }}
    
      - name: Install taosc
        run: |
          curl -sO https://www.taosdata.com/assets-download/3.0/TDengine-client-3.0.7.1-Linux-x64-Lite.tar.gz
          tar zxf TDengine-client-${{ env.TAOS_VERSION }}-Linux-x64-Lite.tar.gz
          cd TDengine-client-${{ env.TAOS_VERSION }}
          ./install_client.sh
            
      - name: Coverage
        run: cargo +nightly tarpaulin --follow-exec --post-test-delay 10 --coveralls ${{ secrets.COVERALLS_REPO_TOKEN }} -- --test-threads=1
