name: Tests

on:
  pull_request:
    types: [opened, synchronize]
    
jobs:
  setup-rust:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
    
  setup-taos:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install taosc
        run: |
          curl -sO https://www.taosdata.com/assets-download/3.0/TDengine-client-3.0.7.1-Linux-x64-Lite.tar.gz
          tar zxf TDengine-client-3.0.7.1-Linux-x64-Lite.tar.gz
          cd TDengine-client-3.0.7.1
          ./install_client.sh
          
  check:
    needs: setup-rust
    runs-on: ubuntu-latest
    
    steps:
      - name: Check format
        run: cargo fmt --check --all
        
      - name: Check clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
  
  tests:
    needs: [setup-rust, setup-taos]
    runs-on: ubuntu-latest
    
    services:
      tdengine:
        image: tdengine/tdengine:3.0.7.1
        ports:
          - 6030:6030
    
    steps:
      - uses: actions/checkout@v3
        
      - name: Test
        run: cargo test
